image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
  - port: 3000
    onOpen: open-preview
tasks:
  - init: mkdir ../go ../go/bin; curl -s "https://raw.githubusercontent.com/gosh-terminal/gosh/master/build" | sh;npm install; node index.js
  - command: gosh